/**
 * Executive Brief Generator — compiles subtask outputs into a structured summary.
 */

interface BriefInput {
  parentTitle: string;
  parentIdentifier: string;
  subtasks: Array<{ identifier: string; title: string; content: string }>;
  apiKey: string;
  baseUrl: string;
  model: string;
}

export async function generateExecutiveBrief(input: BriefInput): Promise<{ brief: string | null; error?: string }> {
  const { parentTitle, parentIdentifier, subtasks, apiKey, baseUrl, model } = input;

  const subtaskSummaries = subtasks
    .map((s) => `### ${s.identifier}: ${s.title}\n${s.content}`)
    .join("\n\n---\n\n");

  const prompt = `You are generating an executive brief that compiles the results of multiple completed subtasks into a clear, actionable summary.

Parent task: ${parentIdentifier} — ${parentTitle}

Completed subtask outputs:
${subtaskSummaries}

Generate a professional executive brief in markdown with these sections:
1. **Summary** — 2-3 sentence overview of the overall findings
2. **Key Findings** — bullet points of the most important discoveries/results
3. **Recommendations** — actionable next steps based on the findings
4. **Sources** — list each subtask identifier and title

Keep it concise and focused on what matters. Do not repeat raw data — synthesize insights.
Format the output as clean markdown starting with: # Executive Brief: ${parentIdentifier} — ${parentTitle}`;

  try {
    const res = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [{ role: "user", content: prompt }],
        max_tokens: 2000,
        temperature: 0.3,
      }),
      signal: AbortSignal.timeout(120_000),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return { brief: null, error: `LLM API error (${res.status}): ${text.substring(0, 200)}` };
    }

    const data = await res.json() as {
      choices?: Array<{ message?: { content?: string } }>;
    };

    const brief = data.choices?.[0]?.message?.content?.trim();
    if (!brief || brief.length < 50) {
      return { brief: null, error: `LLM returned empty/short response (${brief?.length ?? 0} chars)` };
    }

    return { brief: brief + `\n\n---\n*Generated by Paperclip AI | ${new Date().toISOString().split("T")[0]}*` };
  } catch (err) {
    return { brief: null, error: `Brief generation error: ${err instanceof Error ? err.message : String(err)}` };
  }
}
